window.LAB_CONFIG = {
  id: "mcp01",
  reportTitle: "Seven credential failures confirmed",
  reportLabel: "MCP01:2025 · Keys report",
  severity: "High",
  brief: {
    background: "BrokenMCP Corp runs a security scanning platform. Customers connect their code and BrokenMCP scans it for problems.",
    role: "You are keys-auditor, the assistant used by the platform team for credential management.",
    command: "Tools > my_access",
    output: [
      "{",
      "  \"account\": \"keys-auditor\",",
      "  \"role\": \"Auditor\",",
      "  \"scope\": \"cus_4120\",",
      "  \"scope_name\": \"Northwind Health\",",
      "  \"recorded_permissions\": [\"read key metadata\", \"read incident reports\", \"export audit reports\"],",
      "  \"permissions_enforced\": false,",
      "  \"note\": \"Role and scope are recorded on the account and compared with nothing. Nothing in this lab is solved by escalating, so do not bother trying.\"",
      "}",
    ],
  },
  evidence: ["A signing token shipped inside a debug field on a passing health check.","An audit report download link carried the access token in its query string.","A key rotated six months ago still authenticates on its old value.","A key issued in 2023 with no expiry date still authenticates.","A key switched off with revoke_key still authenticates.","A key value the service never issued was accepted because it matched the shape of a real one.","The MCP host config holds a live token in plaintext, in a file tracked by git."],
  fixes: ["Strip debug output before a response leaves the process, and allow-list response fields.","Put credentials in headers, never in a path or query string, and issue links that carry no reusable secret.","Make rotation invalidate the old value at the point of use, not merely record that a newer one exists.","Give every credential a maximum lifetime at issue time and reject any that has none.","Check revocation status on every authentication and fail closed if it cannot be read.","Generate key material from a cryptographic random source, never a counter, and authenticate by looking the value up rather than matching its shape.","Keep tokens out of config files. Reference a secret manager or an environment variable set outside the repository, and scan commits for credentials."],
  challenges: [
    {
      id: "debug_field",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Debug Field",
      task: "Run health check on the key issuing pipeline and read the whole response, not the summary.",
    },
    {
      id: "key_in_url",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Token in the URL",
      task: "Export the credential audit report and check the download URL.",
    },
    {
      id: "stale_rotation",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "Rotated on Paper",
      task: "Incident INC-2291 says the exposed key was rotated. Use the old value and try to authenticate using it.",
    },
    {
      id: "no_expiry",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Key That Never Dies",
      task: "Find the key which has expiry date null. Try to authenticate with it.",
    },
    {
      id: "fake_revocation",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "Revoke Does Nothing",
      task: "We have got 2 defaulter keys/broken keys, first try to revoke it and then try to authenticate with it.",
    },
    {
      id: "forged_key",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "The Key You Made Yourself",
      task: "Work out how key values are built, then write one Keys never issued and authenticate with it.",
    },
    {
      id: "token_in_config",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Token in the Config File",
      task: "The platform team wired keys-auditor up to keys_mcp themselves. Read what they left in env in mcp01-token-mismanagement/.mcp.json, or call read_mcp_config for the same file.",
    },
  ],
};
