window.LAB_CONFIG = {
  id: "mcp08",
  reportTitle: "Six actions nobody can pin on you",
  reportLabel: "MCP08:2025 · Telemetry platform report",
  severity: "High",
  brief: {
    background: [
      "BrokenMCP Corp runs seven systems and they all ship their logs to telemetry_mcp.",
      "It stores three things: the events those systems send, the alarms that fire when a bad event arrives, and a record of who did what on the platform itself.",
      "When something goes wrong anywhere in the company, this is where people look.",
    ],
    command: "Tools > my_account",
    output: [
      "{",
      "  \"account\": \"telemetry-assistant\",",
      "  \"role\": \"analyst\",",
      "  \"contact\": \"telemetry-assistant@brokenmcp.corp\",",
      "  \"capabilities\": [\"search_events\", \"send_events\", \"read_alerts\", \"edit_alert\", \"edit_user\"],",
      "  \"capabilities_i_do_not_hold\": [\"delete_alert\", \"manage_collectors\", \"manage_users\", \"purge_events\"],",
      "  \"my_job\": [",
      "    \"Search the event store when somebody asks what happened.\",",
      "    \"Tune alarms that are too noisy, without switching them off.\",",
      "    \"Keep your own profile and notification address up to date.\"",
      "  ]",
      "}",
    ],
  },
  evidence: ["An audit line was written by hand, naming somebody who did nothing.","Events were destroyed by an account with no right to destroy them.","An alarm was narrowed until it could no longer see the person who narrowed it.","The analysis engine was stopped by one small upload, and the dashboard kept saying healthy.","A capability meant for editing your own profile was used to create an administrator.","Events were deleted through the ingest path, using the platform's own credentials."],
  fixes: ["Neutralise every caller-supplied value before rendering it into a log line, and store fields rather than text.","Check the purge_events capability on the purge path, the way every other privileged path is checked.","Treat narrowing a rule until it excludes the caller as the same power as deleting it, and audit both.","Bound the decompressed size, not the compressed size, and roll component health into the status the dashboard shows.","Scope edit_user to the caller's own account and exclude the role field from it.","Parameterise the bulk write instead of concatenating values into it."],
  challenges: [
    {
      id: "forged_line",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Write A Line As Somebody Else",
      task: "Read the raw audit trail format, then make the fake audit trail action under for user claire.dawson",
    },
    {
      id: "unauthorised_purge",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Destroy Evidence You Cannot Touch",
      task: "purge_events can only be done by admin. Our account role is analyst. Try to delete the events between 14:00 and 14:05",
    },
    {
      id: "rule_exclusion",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "Narrow The Alarm Instead Of Deleting It",
      task: "delete_alert can only be done by an operator. Our account role is analyst. Try to stop the bulk_export alarm from ever firing on our own account, telemetry-assistant.",
    },
    {
      id: "collector_bomb",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "Stop The Analysis Engine",
      task: "Send events in gzip format that are small before unpacking, but too big after unpacking. The engine stops, but the dashboard still looks healthy.",
    },
    {
      id: "omitted_field",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "Two Changes, One Audit Line",
      task: "edit_user can change a contact address or a role. Change both on dozy, then read the audit trail and see whether you can tell the two apart.",
    },
    {
      id: "collector_disabled",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "Switch Off The Recorder",
      task: "Your goal is disable log collector (manage_collectors) which can only be done by an operator. Our account role is analyst.",
    },
  ],
};
