window.LAB_CONFIG = {
  id: "mcp05",
  reportTitle: "Six injection paths confirmed",
  reportLabel: "MCP05:2025 · Console report",
  severity: "High",
  brief: {
    background: [
      "Nobody at BrokenMCP Corp has SSH access to production. That was the security win of the year.",
      "Instead there is a console. You tell it which log to tail, which report to read, which customer to look up, and it runs the command for you. It is the safe way to touch production.",
      "ops_mcp is that console.",
    ],
    role: "You are ops-assistant, acting as dozy.",
    command: "Tools > my_access",
    output: [
      "{",
      "  \"agent\": \"ops-assistant\",",
      "  \"account\": \"dozy\",",
      "  \"role\": \"On-call Engineer\",",
      "  \"task\": \"investigate payments-api errors since the 1 August deploy\",",
      "  \"shell\": \"not available. Commands run through this tool.\",",
      "  \"sanitising\": \"input is checked against a denylist\",",
      "  \"note\": \"There is a control. It is a denylist, and it is checked before anything else.\"",
      "}",
    ],
  },
  evidence: ["A service name carried a second command past a denylist that blocks pipes and not semicolons.","A report path walked out of the reports directory because it was joined and never checked afterwards.","A search term became part of the WHERE clause and returned a table the query never named.","A summary template named the console's own config and the renderer resolved it.","A field a customer typed weeks ago reached a command string, with nobody typing anything malicious.","An argument beginning with a dash was read by tar as an option, and --checkpoint-action=exec= made tar run sh, which read the console config, with no shell and no metacharacter involved."],
  fixes: ["Allowlist the values that reach a command. Never build a command by concatenation.","Resolve the path first, then check the result is inside the base directory. Compare resolved paths, not input strings.","Bind every value. If an identifier cannot be bound, allowlist it against the real schema.","Render against the smallest context that will do. Never hand a renderer an object graph.","Treat a value read from storage exactly like a value typed by a stranger, and validate at the sink.","Terminate caller values with -- and allowlist their shape. Structured arguments are necessary and not sufficient."],
  challenges: [
    {
      id: "shell_metachar",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Semicolon",
      task: "Tail a payments-api log and find way to get content of /srv/ops/config/ops.toml",
    },
    {
      id: "path_traversal",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Path Traversal",
      task: "Read report inc-2291.md and see if you can also read config/ops.toml",
    },
    {
      id: "sql_injection",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "SQL Injection",
      task: "Search for any customer and enumerate the database schema. Goal is to read data from access_token table",
    },
    {
      id: "template_injection",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Template",
      task: "Render a summary with your own body and check whether the tool evaluates it",
    },
    {
      id: "indirect_payload",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "It Came From a Ticket",
      task: "Investigate ticket TK-3312.",
    },
    {
      id: "argument_injection",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "Argument Injection",
      task: "Archive a log path in a way that makes tar do something other than archive it.",
    },
  ],
};
