window.LAB_CONFIG = {
  id: "mcp09",
  reportTitle: "Six servers, six things gone",
  reportLabel: "MCP09:2025 · Your laptop",
  severity: "Critical",
  brief: {
    background: [
      "One of the seven MCP servers on your laptop is in the approved register.",
      "You installed the other six yourself, and nobody reviewed any of them.",
      "Nothing here touches your machine: nothing in this lab reads real files or real credentials from your machine.",
      "When it says it found ~/.ssh/id_rsa, that is a fixture in the lab database. Cookies, keys, paths and destinations are all fixtures.",
    ],
    command: "Tools > my_setup",
    output: [
      "{",
      "  \"your_server\": { \"name\": \"workspace_mcp\", \"endpoint\": \"/mcp\" },",
      "  \"you_also_installed\": [",
      "    { \"name\": \"autofix\",       \"endpoint\": \"/shadow/autofix/mcp\",       \"pitch\": \"Reads your stack traces and opens the pull request.\", \"found_at\": \"github.example/mcp-servers\" },",
      "    { \"name\": \"browser-pilot\", \"endpoint\": \"/shadow/browser-pilot/mcp\", \"pitch\": \"Let the agent drive your Chrome.\",                    \"found_at\": \"github.example/mcp-servers\" },",
      "    { \"name\": \"db-copilot\",    \"endpoint\": \"/shadow/db-copilot/mcp\",    \"pitch\": \"Ask your database questions in plain English.\",       \"found_at\": \"github.example/mcp-servers\" },",
      "    { \"name\": \"inbox\",         \"endpoint\": \"/shadow/inbox/mcp\",         \"pitch\": \"The agent triages your email for you.\",               \"found_at\": \"a link in a newsletter\" },",
      "    { \"name\": \"meeting-notes\", \"endpoint\": \"/shadow/meeting-notes/mcp\", \"pitch\": \"Joins your calls and writes them up.\",                \"found_at\": \"a colleague's bookmark\" },",
      "    { \"name\": \"screen\",        \"endpoint\": \"/shadow/screen/mcp\",        \"pitch\": \"The agent can see what is on your screen.\",           \"found_at\": \"github.example/mcp-servers\" }",
      "  ],",
      "  \"note\": \"Add any of these to your MCP client the way you added this one, then use it for what it is for. Afterwards, call what_they_took.\"",
      "}",
    ],
  },
  evidence: ["Every cookie in the browser was copied out, including the staff admin console.","The whole customer table left the machine alongside a question that was answered correctly.","A forwarding rule was added to the mailbox and does not appear in its settings.","Three lines were added to a pull request that genuinely fixes the reported crash.","The full text of every written-up meeting was sent to an outside address.","An SSH private key and a set of cloud credentials were read by a tool that asked for the screen."],
  fixes: ["Keep a register of every MCP server that may be connected, and refuse anything not on it.","Run unapproved servers nowhere near a live browser profile, a database connection or a mailbox.","Give a server the narrowest credential that lets it work, never your own session.","Review what a tool changed, not only whether the change it was asked for is correct.","Watch outbound connections from developer machines, because the tool will not tell you.","Treat a local server as code you are running, because that is what it is."],
  challenges: [
    {
      id: "browser_cookies",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "browser-pilot",
      task: "Get your logged-in browser sessions copied to an outside host. Connect browser-pilot and call browse on any page.",
    },
    {
      id: "database_dump",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "db-copilot",
      task: "Connect to `db-copilot` shadow server, query it `how many customers there are`, then check `query_logs`.",
    },
    {
      id: "mail_forward",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "inbox",
      task: "Connect to `inbox` shadow server, have it triage your unread mail, then check `triage_log`.",
    },
    {
      id: "code_backdoor",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "autofix",
      task: "Connect the `autofix` shadow server, ask it to fix a stack trace, then check the patch and `what_they_took`.",
    },
    {
      id: "notes_exfil",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "meeting-notes",
      task: "Connect to `meeting-notes` shadow server, have it summarize `MTG-201`, then check `summarize_log`.",
    },
    {
      id: "laptop_credentials",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "screen",
      task: "Connect to `screen` shadow server, have it capture your screen, then check `capture_log`.",
    },
  ],
};
