window.LAB_CONFIG = {
  id: "mcp02",
  reportTitle: "Six escalation paths confirmed",
  reportLabel: "MCP02:2025 · Platform report",
  severity: "High",
  brief: {
    background: [
      "BrokenMCP Corp ships its own software from an internal release platform. Three services live on it: payments-api handles billing, checkout-web is where customers sign up, and infra-manifests is the infrastructure underneath.",
      "Engineers deploy those services to staging and production, run infrastructure jobs, and raise a change request for anything touching production. Every account has a role, and the role decides what you may do.",
      "platform_mcp is where all of that is driven from.",
    ],
    role: "You are dozy, a Viewer account on the platform. Start by asking what you are allowed to do.",
    command: "Tools > my_access",
    output: [
      "{",
      "  \"account\": \"dozy\",",
      "  \"role\": \"viewer\",",
      "  \"permissions\": [\"comment_on_issues\", \"deploy_to_staging\", \"view_logs\", \"view_projects\"],",
      "  \"permissions_from_role\": [],",
      "  \"temporary_grants\": [",
      "    {",
      "      \"account\": \"dozy\",",
      "      \"permission\": \"deploy_to_production\",",
      "      \"granted_by\": \"claire.dawson\",",
      "      \"granted_at\": \"2026-03-12\",",
      "      \"expires_at\": \"2026-03-14\",",
      "      \"justification\": \"INC-4471 hotfix, remove after\",",
      "      \"expired\": true,",
      "      \"status\": \"expired\"",
      "    }",
      "  ],",
      "  \"available_roles\": [\"viewer\", \"deployer\", \"admin\"]",
      "}",
    ],
  },
  evidence: ["A permission that expired on 14 March was still accepted.","A delete ran with no permission check at all.","An account raised its own role to Admin.","A job ran under a shared service account.","A change was approved by the account that raised it.","An access request approved itself."],
  fixes: ["Check the expiry date on every call, not only when the grant is made.","Put one policy decision point in front of every tool and default to deny.","Separate the authority to grant permissions from the authority to use them.","Give every agent its own identity and remove the run_as parameter.","Reject any approval where the approver is the requester.","Review entitlements automatically and alert on grants with no justification."],
  challenges: [
    {
      id: "expired_access",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Expired Permission Still Works",
      task: "Your production access expired on 14 March. Try to deploy any project to production environment.",
    },
    {
      id: "missing_check",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Delete With No Permission Check",
      task: "You are assigned with viewer role, nothing in your permission list mentions deleting. Try to delete any artifact from the production environment.",
    },
    {
      id: "self_promote",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Promote Your Own Account",
      task: "You are dozy and having viewer permissions. change_role was built for the IT admin, and it was never restricted to the IT admin.  Elevate your role to admin.",
    },
    {
      id: "impersonation",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "Borrow the CI Bot's Account",
      task: "Your account cannot run the infra-apply job. The ci-deploy-bot account can. Run infra-apply as the bot.",
    },
    {
      id: "self_approval",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "Approve Your Own Change",
      task: "You raised new PR(pull request) CHG-204, changes need to be approved by admin, try approving with your account (dozy).",
    },
    {
      id: "auto_approval",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "The Request That Approves Itself",
      task: "You don’t have permission to manage accounts, try to elevate your permissions by requesting it.",
    },
  ],
};
