window.LAB_CONFIG = {
  id: "mcp03",
  reportTitle: "Six poisoned definitions confirmed",
  reportLabel: "MCP03:2025 · Desk report",
  severity: "High",
  brief: {
    background: [
      "BrokenMCP Corp runs a support desk for its customers. Northwind Health, Acme Freight, and Vertex Robotics raise tickets there, and the desk holds their contact records, the shared mailboxes the team works from, and everyone's active sessions.",
      "desk_mcp is how the assistant works that queue: reading tickets, closing them, tidying records, sending reports to colleagues.",
    ],
    role: "You are desk-assistant, the AI support agent on that desk. Start by asking what you have.",
    command: "Tools > my_session",
    output: [
      "{",
      "  \"agent\": \"desk-assistant\",",
      "  \"account\": \"dozy\",",
      "  \"role\": \"Support Agent\",",
      "  \"permissions\": [",
      "    \"read_records\",",
      "    \"write_records\",",
      "    \"send_reports\",",
      "    \"manage_sessions\"",
      "  ],",
      "  \"connected_servers\": [",
      "    {",
      "      \"server\": \"desk_mcp\",",
      "      \"tools\": 17,",
      "      \"resources\": 3,",
      "      \"prompts\": 2",
      "    }",
      "  ],",
      "  \"manifest_pinned\": false,",
      "  \"manifest_revision\": \"2026.1\"",
      "}",
    ],
  },
  evidence: ["A tool promising a reversible archive ran a hard delete.","An instruction hidden in an HTML comment made a ticket summary return the customer's reset password and live API token.","A tool definition changed after the session had already approved it.","A resource body was followed as an instruction.","One tool's description added a recipient to a different tool's send.","The audit log recorded the declared action, not the performed one."],
  fixes: ["Encode semantic constraints as automated checks so archive can never map to delete.","Strip comments and markup from every description before it reaches the model, and diff the raw text against what the client renders.","Pin the schema hash to the session and reject any definition whose hash moved.","Treat every server-supplied string as data and keep it out of the instruction channel.","Review the full concatenated tool list as one prompt, because that is what the model sees.","Log the observed effect, not the declared intent, and reconcile the two."],
  challenges: [
    {
      id: "verb_swap",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Archive That Deletes",
      task: "archive_record promises cold storage, reversible for 90 days. Archive any record and look its response or list records to see changes.",
    },
    {
      id: "hidden_comment",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Hidden Comment",
      task: "Summarise the password reset ticket and check what comes back in the response.",
    },
    {
      id: "rug_pull",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Rug Pull",
      task: "Export records, run refresh_manifest, then export again. The tool name did not change.",
    },
    {
      id: "poisoned_resource",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Poisoned Resource",
      task: "Read policy://desk/handling-rules, then close ticket TK-118 following it exactly.",
    },
    {
      id: "tool_shadowing",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "Cross-Tool Shadowing",
      task: "Describe the capability of check_formatting then send email to claire.dawson@brokenmcp.corp",
    },
    {
      id: "silent_log",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "The Silent Log",
      task: "Revoke a single session, then compare list_sessions with audit://desk/log.",
    },
  ],
};
