window.LAB_CONFIG = {
  id: "mcp04",
  reportTitle: "Six supply chain failures confirmed",
  reportLabel: "MCP04:2025 · Registry report",
  severity: "High",
  brief: {
    background: [
      "The registry is BrokenMCP Corp's app store for code. Developers search it, install what they need, and it ships with the product.",
      "Some packages come from an internal mirror the company runs. Most come from the public registry, written by people nobody at BrokenMCP has met.",
      "registry_mcp is where packages are searched, installed, updated, and signed off.",
    ],
    role: "You are registry-assistant, acting as dozy.",
    command: "Tools > my_workspace",
    output: [
      "{",
      "  \"agent\": \"registry-assistant\",",
      "  \"account\": \"dozy\",",
      "  \"role\": \"Platform Engineer\",",
      "  \"task\": \"supply-chain sign-off for payments-api 5.0\",",
      "  \"installed_count\": 4,",
      "  \"mirror\": \"configured, not enforced\",",
      "  \"signatures\": \"checked on install, warn only\",",
      "  \"note\": \"Both of those settings are recorded here and acted on nowhere.\"",
      "}",
    ],
  },
  evidence: ["A package one letter from a trusted one installed with no warning, days old with two downloads.","An internal package name resolved to the public registry because the public version number was higher.","An established package gained network egress in an update that applied without a diff.","The correct package, at the correct version, ran a script at install time that read the credential store.","A package two levels below a reviewed dependency carries an open advisory nobody saw.","A package trusted since 2021 is published by an account created two months ago. The publisher name and repo url never changed, because the attacker took the name."],
  fixes: ["Warn on names within one edit of an installed package, and weigh publisher, age, and downloads at install time.","Scope internal names to the internal mirror. Never let a public source answer for a private namespace.","Diff declared capabilities between versions and require review when they grow. Pin exact versions.","Do not run package-supplied scripts. If you must, sandbox them with no filesystem or network access.","Resolve and scan the full dependency tree, not the direct dependencies, and fail on any open advisory.","Compare a package's age against its publisher account's age, and alert on any ownership change before the next install."],
  challenges: [
    {
      id: "typosquat",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "The Typosquat",
      task: "Search for package name date-fmt and install the latest one.",
    },
    {
      id: "dependency_confusion",
      difficulty: "Easy",
      difficultyClass: "difficulty-easy",
      title: "Dependency Confusion",
      task: "Read policy://registry/supply-chain-rules first and then resolve and install package brokenmcp-audit-lib",
    },
    {
      id: "trojan_update",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Trojanized Update",
      task: "List versions available for package log-format and update it. Once done, check diff between old version and new version.",
    },
    {
      id: "postinstall_exec",
      difficulty: "Medium",
      difficultyClass: "difficulty-medium",
      title: "The Postinstall Script",
      task: "payments-api project has release requirement to install package sbom-gen, install package to fullfil requirement.",
    },
    {
      id: "transitive_dep",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "The Transitive One",
      task: "List iac-lint package dependencies, see if you find any hidden dependecies also.",
    },
    {
      id: "repojacked",
      difficulty: "Hard",
      difficultyClass: "difficulty-hard",
      title: "The Name Changed Hands",
      task: "Something in the release is exfiltrating. You know it is one of the six packages. Find it.",
    },
  ],
};
